### Spring properties
# Service registers under this name
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_management_sys?useSSL=false
    username: root
    password: root
  application:
    name: library-dao
  
# Discovery Server Access
eureka:
    instance:
      prefer-ip-address: false 
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8090/eureka/
        register-with-eureka: false
      fetch-registry: false
  
# HTTP Server (Tomcat) Port
server: 
  port: 8092

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
